// -------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Health.Fhir.Core.Features.Search;
using MongoDB.Bson;
using MongoDB.Driver;

namespace Microsoft.Health.Fhir.MongoDb.Features.Search.Queries
{
    internal interface IQueryBuilder
    {
#pragma warning disable CS8625
        /// <summary>
        /// Takes in a SearchOptions object generated by the FHIR server and
        /// produces a MongoDb Filter Expression to be executed against the FHIR store.
        /// </summary>
        /// <param name="searchOptions">expression definition of search to parsed into MongoDb query</param>
        /// <returns>A BsonDocument Document containing a MongoDb filter definition</returns>
        BsonDocument BuildFilterSpec(SearchOptions searchOptions);
#pragma warning restore CS8625
    }
}
